### ISSUE TITLE
AVANE for iOS and Android

### ISSUE THREAD

**Issue by dnikolaev** [tuarua/AVANE#1]
Hi @tuarua Eoin,

Have you planned to add iOS and Android support for this ANE? I think a lot of people would be interested in it.

Best regards,
Dmitrii

**Comment by tuarua** [comment]
Hi @dnikolaev Dmitri,
Thanks for your question,

I have briefly looked at Android. I should be able to use this as a starting-off-point.
http://writingminds.github.io/ffmpeg-android-java/

I do first want to get the ANE working on OSX.

**Comment by dnikolaev** [comment]
Thank you so much.

I'll follow your repository.

**Comment by tuarua** [comment]
Hi @dnikolaev Dmitri,
Just to let you know I haven't forgotten about this.
I am currently working on the Android version. It's quite technically intricate with cross compiling FFmpeg to Android and leveraging JNI and but I'm working through it.

**Comment by dnikolaev** [comment]
Hi @tuarua,

Thank you so much. I'm looking forward for update.

If you need I'll help with testing on Android (4.x, 5.x, 6.x).

**Comment by tuarua** [comment]
Hi Dmitri,
I have now committed the initial Android version of the ANE with full source code.
Some notes:
- I compiled FFmpeg with x264 support initially. There is lots of room for tweaking, ie adding removing codecs and trimming out things that may not be needed.
- I targeted minimum version of 4.4 (aka 19)
- Improved AIR example to follow
- I also abstracted the Android part into a library of it's own. This allows it to be used by native Android apps.
  eg.
  https://github.com/tuarua/LibAVANE-Android-Example

**Comment by dnikolaev** [comment]
Hi Eoin,

How incredible! We'll test it as soon as possible.

Regards,
Dmitrii

**Comment by marchbold** [comment]
Great work here! 

Just had a request to build something very similar but might just help out on this one if you're looking for contributors?

**Comment by tuarua** [comment]
I've made a start on the iOS version. Getting through it slowly. Trying to reuse as much of the OSX code as possible.
Initially I can only build and test on the simulator as I don't own an ipad or iphone! As such I'll struggle to build the release version. 
So @marchbold , this is where I am happy to take on a contributor to help. Your experience with creating many ANEs for iOS and Android would be appreciated.
I hope to have something by next week. There's quite a bit of dependency packaging/tweaking to do and is the main reason I didn't release the full source for Win yet.

**Comment by tuarua** [comment]
Source code for iOS now uploaded and compiled version of the ANE for simulator only.

**Comment by marchbold** [comment]
Great, I'll have a look over it and test on some of our iOS devices.

**Comment by tuarua** [comment]
Cool, one thing to be aware of. There is a RUNME.sh script in the dependencies folder. You'll need to run this to download required libs (x264, FFmpeg and boost) They are all FAT libs so include all the archs.

**Comment by tuarua** [comment]
iOS is now fully supported. 
Android supported as much as FFmpeg allows.

**Comment by dnikolaev** [comment]
@tuarua Thank you so much! I'll try to test it as soon as possible.
