### ISSUE TITLE
Weird error when starting AVANE the 2nd time

### ISSUE THREAD

**Issue by Igazine** [tuarua/AVANE#12]
A weird error occurs if I start a live capture (dshow) the 2nd time during the same app session.

First everything works perfectly, then I stop avane with cancelEncode(). If I start the encoding process again with exactly the same parameters, it fails to read any input from the capture device. It looks like some buffer is not getting flushed, can't really say for sure what's wrong. Here's the trace output of the second encoding process:

```
...
message Picture size 53247x16256 is invalid
message Error while decoding stream #0:0: Invalid data found when processing input
message decode_sos: nb_components (0) unsupported
...
```

The encoding never starts and after a minute or so avane exits.

I tried avane.dispose(), InputStream.clear(), reinitialise the instance and to create a new instance - the same error happens every time.

Here's the classicString if you're interested:

`-y -thread_queue_size 512 -f dshow -vcodec mjpeg -s 1280x720 -framerate 30 -i video="HD 720P Webcam" -c:v libx264 -flags +global_header -pix_fmt yuv420p -b:v 1500k -bufsize 3000k -vf scale=-1:720 -r 30 -g 60 -force_key_frames 2 -copytb 1 -tune zerolatency -preset ultrafast -f tee -map 0:0 [f=flv]rtmp://localhost:1935/LiveBroadcaster/LiveStream`

**Comment by Igazine** [comment]
you can see the crazy large picture size, i can assure you i did not set a size that large :)

**Comment by Igazine** [comment]
I tried it with the simplest parameters possible, same result after the 2nd try

`avane.encode( '-y -f dshow -i video="HD 720P Webcam" test.mp4' );`

**Comment by tuarua** [comment]
I'll have a look tonight. Thanks for raising. I'll also email re: other things shortly

**Comment by tuarua** [comment]
I'm not able to replicate the issue using the example project.
I am using UScreenCapture.

1) Are you able to use replicate using the provided example but using your webcam? 
2) And Are you able to use replicate using the provided example but using UScreenCapture ?

**Comment by Igazine** [comment]
I can't get UScreenCapture to show up on Windows.
However there's ManyCam, a free virtual webcam, you can try it, 2nd time it doesn't even start (the error also never shows up, like with a real webcam). it's really weird

`avane.encode( '-y -f dshow -i video="ManyCam Virtual Webcam" test.mp4' );`

**Comment by tuarua** [comment]
I installed ManyCam and it worked too with no problems.
