### ISSUE TITLE
Trying to play hls stream on Android

### ISSUE THREAD

**Issue by kerike** [tuarua/AVANE#13]
Hi,

first of all great job, this project is awesome. I am trying to play hls stream on Android, and found your ANE.

I tried using the ANE in a project but the IDE sais: extension xml is not present or is invalid.
I am using FB 4,6, could that be the problem?

My second question is that would it be possible to play hls stream on Android? If it is not possible at all, and some people say it is not, then I should look for another solution.

Thank you for your great work and your answer.

Istvan Keresztes.

**Comment by tuarua** [comment]
1. Are you using the one for Android, i.e.. AVANE-android.ane?
What AIRSDK are you using

2. I would have to check. The ANE can convert HLS. It would then have to 'stream' it into flash video. This uses appendBytes and I don't believe that's currently working on Android

**Comment by kerike** [comment]
Hi,

I am using the AVANE-android.ane. Flash Builder 4.6 AIRSDK 24, -swf-version=35. I tried with other sdk versions and still getting: extension xml is not present or is invalid.

What I would like to note, is that with other ANE-s I could open them with winrar. Opening AVANE-android.ane with winrar gives me: The archive is either in unknown format or damaged.

Thank you for your help.

**Comment by tuarua** [comment]
ok, sounds like the ane got corrupted when you downloaded it.
Are you able to open the other ANEs in the folder with Winrar?
How are you downloading from GitHub, by using Download as zip or using Git tool or command line.
I did a Git checkout/pull on the ANEs on my Windows machine and they are valid zips for me.
Can you try checking everything out again.

**Comment by kerike** [comment]
Hi,

first I have downloaded the repository as zip. Now I tried to checkout with git GUI, and still all the ANE-s are corrupted. I have tried all of them, AVANE, AVANE-android, AVANE-ios.

Could you please send me yours to my email? kerike2002@yahoo.com

Thank you.

**Comment by tuarua** [comment]
I can't email. The files are at least 50MB each.
I honestly don't know why you are getting them as corrupt. They are fine for me.

**Comment by kerike** [comment]
Hi,

I figured something out :). When you said that all your ane-s are 50MB large, I looked at my corrupted ones, and they are 1MB large. Then I entered on github to where the ANE is, an clicked on download only for that file...and voila...I have the 50MB ANE

Time to start testing...

Thank you for your time and patience

**Comment by tuarua** [comment]
No problem, with regards to HLS, please see what I said earlier. AVANE is not meant to be a one-stop-shop for everything. It's essentially a port of FFmpeg - which is meant for encoding. It *may* be used creatively (like I did on Desktop) to convert videos into flv and play back. Phones are more restrictive in terms of horsepower so going for a native video player ANE from Distriqt or MyFlashLabs may be better.

**Comment by kerike** [comment]
Thank you very much for your help. Will look into those possibilities too.
