### ISSUE TITLE
Issue when converting consecutive files

### ISSUE THREAD

**Issue by rjx444** [tuarua/AVANE#14]
Hi sir,
Good day! :) I am now using your ANE to convert video files. I implemented it in a way that the user can browse and select the file that they want to convert but unfortunately after the first file has been converted, and the user selects another file, it will process the conversion but the strange thing is that the content of the file is the same with the first video that is converted. I already checked and tried to debug the issue, and made sure that the encoding is pointing on the right file url, but the issue is still there. Do you have any idea sir what causes the issue? Will wait for your kind response good sir. :)
Thanks

**Comment by tuarua** [comment]
Hello.
Which platform are your using, iOS Android Win or OSX ?
Please provide a log.
Set the Loglevel accordingly
avANE.setLogLevel(LogLevel.VERBOSE);
This will trace the log into FB console.

**Comment by rjx444** [comment]
Hi sir,
I'm using android. It seems that the inputstream and outputoptions is not being cleared. 
Here is the log:

 [ffmpeg][flv][warning] : audio stream discovered after head already parsed
 [ffmpeg][flv][warning] : video stream discovered after head already parsed
constructed FFmpeg cli sent to encode: -nostdin,-y,-i,/storage/emulated/0/Download/SampleVideo_1280x720_1mb.flv,-map,0:a:0,-c:a:0,aac,-ar:a:0,48000,-ab:a:0,96000,-ac,2,-map,0:v:0,-c:v:0,libx264,-b:v:0,0,-preset:v:0,ultrafast,-crf,20,-movflags,+faststart,-metadata,description=The description,-metadata,title=AVANE encoded video,/data/data/air.com.edno.EdnoCommForTeachers.debug/com.edno.EdnoCommForTeachers.debug/Local Store/SampleVideo_1280x720_1mb.mp4
 [ffmpeg][][info] : Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Download/VID_20170110_102222.3gp':
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : major_brand     :
 [ffmpeg][][info] : 3gp4
 [ffmpeg][][info] : minor_version   :
 [ffmpeg][][info] : 0
 [ffmpeg][][info] : compatible_brands:
 [ffmpeg][][info] : isom3gp4
 [ffmpeg][][info] : creation_time   :
 [ffmpeg][][info] : 2017-01-10T02:22:22.000000Z
 [ffmpeg][][info] : com.android.version:
 [ffmpeg][][info] : 6.0
 [ffmpeg][][info] : Duration:
 [ffmpeg][][info] : 00:00:04.59
 [ffmpeg][][info] : , start:
 [ffmpeg][][info] : 0.000000
 [ffmpeg][][info] : , bitrate:
 [ffmpeg][][info] : 3955 kb/s
 [ffmpeg][][info] : Stream #0:0
 [ffmpeg][][info] : (eng)
 [ffmpeg][][info] : : Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 3955 kb/s
 [ffmpeg][][info] : ,
 [ffmpeg][][info] : 30 fps,
 [ffmpeg][][info] : 30 tbr,
 [ffmpeg][][info] : 90k tbn,
 [ffmpeg][][info] : 300 tbc
 [ffmpeg][][info] : (default)
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : rotate          :
 [ffmpeg][][info] : 90
 [ffmpeg][][info] : creation_time   :
 [ffmpeg][][info] : 2017-01-10T02:22:22.000000Z
 [ffmpeg][][info] : handler_name    :
 [ffmpeg][][info] : VideoHandle
 [ffmpeg][][info] : Side data:
 [ffmpeg][][info] : displaymatrix: rotation of -90.00 degrees
 [ffmpeg][][info] : Stream #0:1
 [ffmpeg][][info] : (eng)
 [ffmpeg][][info] : : Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s
 [ffmpeg][][info] : (default)
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : creation_time   :
 [ffmpeg][][info] : 2017-01-10T02:22:22.000000Z
 [ffmpeg][][info] : handler_name    :
 [ffmpeg][][info] : SoundHandle
 [ffmpeg][flv][warning] : audio stream discovered after head already parsed
 [ffmpeg][flv][warning] : video stream discovered after head already parsed
 [ffmpeg][][info] : Input #1, flv, from '/storage/emulated/0/Download/SampleVideo_1280x720_1mb.flv':
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : encoder         :
 [ffmpeg][][info] : Lavf53.24.2
 [ffmpeg][][info] : Duration:
 [ffmpeg][][info] : 00:00:05.16
 [ffmpeg][][info] : , start:
 [ffmpeg][][info] : 0.000000
 [ffmpeg][][info] : , bitrate:
 [ffmpeg][][info] : 1629 kb/s
 [ffmpeg][][info] : Stream #1:0
 [ffmpeg][][info] : : Audio: aac (LC), 48000 Hz, 5.1, fltp
 [ffmpeg][][info] : Stream #1:1
 [ffmpeg][][info] : : Video: flv1, yuv420p, 1280x720
 [ffmpeg][][info] : ,
 [ffmpeg][][info] : 25 fps,
 [ffmpeg][][info] : 25 tbr,
 [ffmpeg][][info] : 1k tbn
 [ffmpeg][libx264][info] : using SAR=1/1
 [ffmpeg][libx264][info] : using cpu capabilities: none!
 [ffmpeg][libx264][info] : profile Constrained Baseline, level 3.0
 [ffmpeg][libx264][info] : 264 - core 148 r2721 72d53ab - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=20.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
 [ffmpeg][libx264][info] : using SAR=1/1
 [ffmpeg][libx264][info] : using cpu capabilities: none!
 [ffmpeg][libx264][info] : profile Constrained Baseline, level 3.0
 [ffmpeg][libx264][info] : 264 - core 148 r2721 72d53ab - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=20.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
 [ffmpeg][][info] : Output #0, mp4, to '/data/data/air.com.edno.EdnoCommForTeachers.debug/com.edno.EdnoCommForTeachers.debug/Local Store/VID_20170110_102222.mp4':
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : major_brand     :
 [ffmpeg][][info] : 3gp4
 [ffmpeg][][info] : minor_version   :
 [ffmpeg][][info] : 0
 [ffmpeg][][info] : compatible_brands:
 [ffmpeg][][info] : isom3gp4
 [ffmpeg][][info] : com.android.version:
 [ffmpeg][][info] : 6.0
 [ffmpeg][][info] : description     :
 [ffmpeg][][info] : The description
 [ffmpeg][][info] : title           :
 [ffmpeg][][info] : AVANE encoded video
 [ffmpeg][][info] : encoder         :
 [ffmpeg][][info] : Lavf57.51.102
 [ffmpeg][][info] : Stream #0:0
 [ffmpeg][][info] : (eng)
 [ffmpeg][][info] : : Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp, 96 kb/s
 [ffmpeg][][info] : (default)
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : creation_time   :
 [ffmpeg][][info] : 2017-01-10T02:22:22.000000Z
 [ffmpeg][][info] : handler_name    :
 [ffmpeg][][info] : SoundHandle
 [ffmpeg][][info] : encoder         :
 [ffmpeg][][info] : Lavc57.60.101 aac
 [ffmpeg][][info] : Stream #0:1
 [ffmpeg][][info] : (eng)
 [ffmpeg][][info] : : Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 480x640 [SAR 1:1 DAR 3:4], q=-1--1
 [ffmpeg][][info] : ,
 [ffmpeg][][info] : 30 fps,
 [ffmpeg][][info] : 15360 tbn,
 [ffmpeg][][info] : 30 tbc
 [ffmpeg][][info] : (default)
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : handler_name    :
 [ffmpeg][][info] : VideoHandle
 [ffmpeg][][info] : creation_time   :
 [ffmpeg][][info] : 2017-01-10T02:22:22.000000Z
 [ffmpeg][][info] : encoder         :
 [ffmpeg][][info] : Lavc57.60.101 libx264
 [ffmpeg][][info] : Side data:
 [ffmpeg][][info] : cpb:
 [ffmpeg][][info] : bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
 [ffmpeg][][info] : Output #1, mp4, to '/data/data/air.com.edno.EdnoCommForTeachers.debug/com.edno.EdnoCommForTeachers.debug/Local Store/SampleVideo_1280x720_1mb.mp4':
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : major_brand     :
 [ffmpeg][][info] : 3gp4
 [ffmpeg][][info] : minor_version   :
 [ffmpeg][][info] : 0
 [ffmpeg][][info] : compatible_brands:
 [ffmpeg][][info] : isom3gp4
 [ffmpeg][][info] : com.android.version:
 [ffmpeg][][info] : 6.0
 [ffmpeg][][info] : description     :
 [ffmpeg][][info] : The description
 [ffmpeg][][info] : title           :
 [ffmpeg][][info] : AVANE encoded video
 [ffmpeg][][info] : encoder         :
 [ffmpeg][][info] : Lavf57.51.102
 [ffmpeg][][info] : Stream #1:0
 [ffmpeg][][info] : (eng)
 [ffmpeg][][info] : : Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp, 96 kb/s
 [ffmpeg][][info] : (default)
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : creation_time   :
 [ffmpeg][][info] : 2017-01-10T02:22:22.000000Z
 [ffmpeg][][info] : handler_name    :
 [ffmpeg][][info] : SoundHandle
 [ffmpeg][][info] : encoder         :
 [ffmpeg][][info] : Lavc57.60.101 aac
 [ffmpeg][][info] : Stream #1:1
 [ffmpeg][][info] : (eng)
 [ffmpeg][][info] : : Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 480x640 [SAR 1:1 DAR 3:4], q=-1--1
 [ffmpeg][][info] : ,
 [ffmpeg][][info] : 30 fps,
 [ffmpeg][][info] : 15360 tbn,
 [ffmpeg][][info] : 30 tbc
 [ffmpeg][][info] : (default)
 [ffmpeg][][info] : Metadata:
 [ffmpeg][][info] : handler_name    :
 [ffmpeg][][info] : VideoHandle
 [ffmpeg][][info] : creation_time   :
 [ffmpeg][][info] : 2017-01-10T02:22:22.000000Z
 [ffmpeg][][info] : encoder         :
 [ffmpeg][][info] : Lavc57.60.101 libx264
 [ffmpeg][][info] : Side data:
 [ffmpeg][][info] : cpb:
 [ffmpeg][][info] : bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
 [ffmpeg][][info] : Stream mapping:
 [ffmpeg][][info] : Stream #0:1 -> #0:0
 [ffmpeg][][info] : (aac (native) -> aac (native))
 [ffmpeg][][info] : Stream #0:0 -> #0:1
 [ffmpeg][][info] : (mpeg4 (native) -> h264 (libx264))
 [ffmpeg][][info] : Stream #0:1 -> #1:0
 [ffmpeg][][info] : (aac (native) -> aac (native))
 [ffmpeg][][info] : Stream #0:0 -> #1:1
 [ffmpeg][][info] : (mpeg4 (native) -> h264 (libx264))
 [ffmpeg][][info] : frame=    0 fps=0.0 q=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x
 [ffmpeg][][info] : frame=    0 fps=0.0 q=0.0 q=0.0 size=       0kB time=00:00:00.83 bitrate=   0.5kbits/s speed=1.66x
 [ffmpeg][][info] : frame=    9 fps=8.7 q=22.0 q=22.0 size=      64kB time=00:00:01.02 bitrate= 508.0kbits/s speed=0.994x
 [ffmpeg][][info] : frame=   16 fps= 10 q=22.0 q=22.0 size=     169kB time=00:00:01.02 bitrate=1340.5kbits/s speed=0.669x
 [ffmpeg][][info] : frame=   24 fps= 12 q=21.0 q=21.0 size=     298kB time=00:00:01.02 bitrate=2368.3kbits/s speed=0.498x
 [ffmpeg][][info] : frame=   29 fps= 11 q=22.0 q=22.0 size=     371kB time=00:00:01.34 bitrate=2249.5kbits/s speed=0.525x
 [ffmpeg][][info] : frame=   35 fps= 11 q=21.0 q=21.0 size=     472kB time=00:00:02.03 bitrate=1902.5kbits/s speed=0.659x
 [ffmpeg][][info] : frame=   44 fps= 12 q=22.0 q=22.0 size=     613kB time=00:00:02.03 bitrate=2472.5kbits/s speed=0.556x
 [ffmpeg][][info] : frame=   52 fps= 12 q=22.0 q=22.0 size=     732kB time=00:00:02.03 bitrate=2949.8kbits/s speed=0.488x
 [ffmpeg][][info] : frame=   60 fps= 13 q=22.0 q=22.0 size=     851kB time=00:00:02.05 bitrate=3395.0kbits/s speed=0.431x
 [ffmpeg][][info] : frame=   60 fps= 11 q=22.0 q=22.0 size=     851kB time=00:00:02.97 bitrate=2346.8kbits/s speed=0.564x
 [ffmpeg][][info] : frame=   69 fps= 12 q=22.0 q=22.0 size=     981kB time=00:00:03.03 bitrate=2647.8kbits/s speed=0.524x
 [ffmpeg][][info] : frame=   77 fps= 12 q=23.0 q=23.0 size=    1112kB time=00:00:03.03 bitrate=3000.3kbits/s speed=0.479x
 [ffmpeg][][info] : frame=   86 fps= 13 q=21.0 q=21.0 size=    1266kB time=00:00:03.03 bitrate=3415.7kbits/s speed=0.444x
 [ffmpeg][][info] : frame=   91 fps= 12 q=22.0 q=22.0 size=    1335kB time=00:00:03.24 bitrate=3367.1kbits/s speed=0.442x
 [ffmpeg][][info] : frame=   96 fps= 12 q=23.0 q=23.0 size=    1399kB time=00:00:04.03 bitrate=2839.0kbits/s speed=0.514x
 [ffmpeg][][info] : frame=  103 fps= 12 q=22.0 q=22.0 size=    1497kB time=00:00:04.03 bitrate=3036.7kbits/s speed=0.481x
 [ffmpeg][][info] : frame=  112 fps= 13 q=21.0 q=21.0 size=    1637kB time=00:00:04.03 bitrate=3321.1kbits/s speed=0.453x
 [ffmpeg][][info] : frame=  121 fps= 13 q=21.0 q=21.0 size=    1782kB time=00:00:04.03 bitrate=3616.1kbits/s speed=0.428x
 [ffmpeg][][info] : frame=  129 fps= 13 q=21.0 q=21.0 size=    1919kB time=00:00:04.05 bitrate=3871.8kbits/s speed=0.408x
 [ffmpeg][mp4][info] : Starting second pass: moving the moov atom to the beginning of the file
 [ffmpeg][mp4][info] : Starting second pass: moving the moov atom to the beginning of the file
 [ffmpeg][][info] : frame=  133 fps= 12 q=-1.0 Lq=-1.0 size=    2112kB time=00:00:04.61 bitrate=3749.4kbits/s speed=0.432x
 [ffmpeg][][info] : video:4104kB audio:109kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead:
 [ffmpeg][][info] : unknown

**Comment by tuarua** [comment]
ok, I see what you mean. I will have a look

**Comment by tuarua** [comment]
I will look at this! The codebase is HUGE so may take a few days to track down

**Comment by rjx444** [comment]
Thank you sir. Will be waiting for it :)

**Comment by tuarua** [comment]
Hi, this should now be fixed. Be aware that due to their size the ANEs are now on Git LFS. If you have trouble pulling them (or they are 1MB when downloaded) then you may need to manually download them from a browser. Some users have trouble with LFS zips.

**Comment by rjx444** [comment]
Thanks for the big help sir. I'll try this out. Also does this fix includes also the ane for ios?

**Comment by Igazine** [comment]
I think I experienced the same on desktop in issue #12

**Comment by tuarua** [comment]
The bug was inputContext.commandLine.clear(); was missing from the encode method in Android version ONLY. iOS, Win and OSX share the same source code. Android is separate.
This is not related to Issue #12

**Comment by rjx444** [comment]
Noted sir. I haven't tried it out yet but really thanks for the help. I'll update you after my testing :)

**Comment by rjx444** [comment]
Git it working sir for android! thanks a lot :)
