### ISSUE TITLE
ANE Error when building app in ios

### ISSUE THREAD

**Issue by rjx444** [tuarua/AVANE#15]
Hi sir,
The android ane is really doing great but when I tried to build my app in ios it gives me this error:
![ane-error](https://cloud.githubusercontent.com/assets/12758745/22362587/9a7457d8-e49e-11e6-937f-c01c40adca7e.png)
Please advice.

Thanks once again :)

**Comment by tuarua** [comment]
I had to do the following. iOS is difficult for all AIR apps at the mo.
1. Install Xcode8.2
2. Follow Mayank_Gupta's post carefully on https://forums.adobe.com/thread/2209195. 
3. Set your Apple iOS SDK in IntelliJ/Flash Builder to: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk. Ignore any warnings.

_Please note I am using IntelliJ on my mac. The above works for me. I am unable to verify Flash Builder at this moment_

**Comment by rjx444** [comment]
I see... Currently I'm using windows 7 and don't have any ios device. Thanks for the instructions sir. Will try to find a way, maybe will install a VM.

**Comment by tuarua** [comment]
You need a mac to compile AIR apps for iOS and to sign, provision and publish to the app store. 
Android is easy, iOS is not.
It's just he way it is.
