### ISSUE TITLE
Extension XML is not present or is invalid

### ISSUE THREAD

**Issue by outboks** [tuarua/AVANE#19]
i have this message on native extension window on flash builder, i think its missing the extension.xmk for AVANE and SaveAsANE, could u please upload the files for WIN and OSX?

thank you so much for sharing this

**Comment by tuarua** [comment]
Hello
I use GitHub Large File Storage for these files and it is causing lots of people problems with some GitHub clients, as it corrupts .ane files for some reason.

Please download the files direct from your browser.

https://github.com/tuarua/AVANE/blob/master/native_extension/ane/SaveAsANE.ane?raw=true
https://github.com/tuarua/AVANE/blob/master/native_extension/ane/AVANE.ane?raw=true

I will add a note to the README

**Comment by outboks** [comment]
Yes correct, the .ane is corrupted, all is well now, thank you so much for this :)
