### ISSUE TITLE
Audio - Wav to MP3 Conversion

### ISSUE THREAD

**Issue by dannycortesv** [tuarua/AVANE#20]
Is it possible to add wav to mp3 conversion? Wondering if i can do that with AVANE, thank you for your amazing support! :)

**Comment by tuarua** [comment]
WIN and OSX for sure supports converting from wav to mp3.

eg
`avane.encode("-i input.wav -codec:a libmp3lame -qscale:a 2 output.mp3");`

Use settings as per this page
https://trac.ffmpeg.org/wiki/Encode/MP3

**Comment by dannycortesv** [comment]
Wow, that's great! Doing this on mobile is very heavy right? I'm doing a voice recording app, but .wav files has a big size, any path do you suggest me to reduce files size, any other format or configurations?

**Comment by tuarua** [comment]
mp3 encoding is only in the Desktop versions of AVANE
Doing on mobile is heavy yes. I also didn't compile with LAME codec for mobile.
The mobile versions of the ANE were cool experiments and a good learning experience but it would be much better to write an ANE which utilised the core libraries of Android and iOS.

According to the guide there are few settings.
The guide recommends using between -qscale:a 0 to -qscale:a 3.
I haven't personally encoded much mp3 in a long time.
