### ISSUE TITLE
WIN dll  debug

### ISSUE THREAD

**Issue by nidiy** [tuarua/AVANE#21]
Windows dll seems to be using debug mode?

**Comment by tuarua** [comment]
Can you explain what you mean??
Please give more detail.

**Comment by nidiy** [comment]
PC on the package exe, in other computers need to manually increase the dynamic library in order to normal operation.
![image](https://oityq0cxd.qnssl.com/2017-08-31_59a76f15467c0.jpg?e=1504148775&token=-YdeH6WvESHZKz-yUzWjO-uVV6A7oVrCN3UXi48F:sLoT30kCkHWgIDz6xLTdEK4fZXg=)

**Comment by tuarua** [comment]
Yes you need to have Microsoft Visual C++ 2015 Redistributable installed on users machines as the ANE was built with Visual Studio. This is normal for C++ projects/apps and most machines have it.
When building an app using an installer which checks for dependancies is advisable.

I still don't know what you mean by the dll being debug mode.

**Comment by nidiy** [comment]
Ok, Thanks
