### ISSUE TITLE
multiple input video, multiple output screenshot

### ISSUE THREAD

**Issue by varadig** [tuarua/AVANE#22]
I have multiple videofile, and I have to generate screenshots from them.
How can I solve to do in one shot?

Thanks

**Comment by varadig** [comment]
I can do it with classic usage like this:

```
var ffmpeg:AVANE = new AVANE();
ffmpeg.encode("-ss 00:00:00 -i " + file.url + " -vframes 1 -q:v 2 " + folder.resolvePath(file.name).url + ".jpg");

```

but I cant add multiple input and output.

I wanted to know, how can I do it with AVANE options?

**Comment by tuarua** [comment]
It's not possible to combine multiple inputs and outputs in a single encode call.
If you want to convert multiple files then you listen for the complete event and then run a new separate encode call

e.g.

```
ffmpeg.addEventListener(FFmpegEvent.ON_ENCODE_FINISH,onEncodeFinish);
ffmpeg.encode("-ss 00:00:00 -i " + file.url + " -vframes 1 -q:v 2 " + folder.resolvePath(file.name).url + ".jpg");

function onEncodeFinish(event:FFmpegEvent){
    ffmpeg.encode("-ss 00:00:00 -i " + file2.url + " -vframes 1 -q:v 2 " + folder.resolvePath(file2.name).url + ".jpg");
}
```

**Comment by varadig** [comment]
Ohh thanks, thats enough for me!

**Comment by varadig** [comment]
Maybe would be useful, if could be add queue encoding processes.
