### ISSUE TITLE
Desktop capture 

### ISSUE THREAD

**Issue by janZhao** [tuarua/AVANE#24]
您好：
我  using screen-capture-recorder to capture desktop in Windows，
 请问是否 支持 以 将桌面的画面和麦克风的声音以rtmp流的形式推送到 FMS流媒体服务器上面呢？

**Comment by tuarua** [comment]
Probably.
You should use the encode method to pass in an FFmpeg command
avANE.encode("[FFMPEG command]");

eg
-f dshow -i video="screen-capture-recorder" -vf crop=690:388:136:0 -r 30 -s 962x388 -threads 2 -vcodec libx264 -vpre baseline -f flv rtmp:///live/myStream.sdp

You will need to read the FFmpeg guide. AVANE is just a wrapper around FFmpeg.
It doesn't provide magic one line pieces of code. I don't provide complete solutions answers to such a broad question. If you want to build a product you will need to do the research / work yourself.

https://trac.ffmpeg.org/wiki/StreamingGuide
