### ISSUE TITLE
Does it support to seek a  playing video at some frame or time?

### ISSUE THREAD

**Issue by samchild** [tuarua/AVANE#3]
hi @tuarua , 
how can i use the AVANE to play a mp4 or flv file  and then seek to particular time/frame(not just key frame I-Frame) backward or toward?
Does this feature will be available in future?

**Comment by tuarua** [comment]
AVANE is an implementation of FFmpeg for AIR projects. It is primarily used for transcoding video from 1 format to another. The examples I wrote show the different ways this library could be used.
That being said.
Please see the updated Universal Player example which shows how to seek a video.

For example if your video has a framerate of 25 fps and you wanted to seek to 10 seconds and 2 frames you would do this:
`inputOptions.startTime = 10.08;`

Please also read the following guide from FFmpeg carefully.
[https://trac.ffmpeg.org/wiki/Seeking](https://trac.ffmpeg.org/wiki/Seeking)

**Comment by samchild** [comment]
Thank you every much!!!
