### ISSUE TITLE
InputOptions.frameRate should be Number type

### ISSUE THREAD

**Issue by Igazine** [tuarua/AVANE#4]
Hi,

First, I LOVE your work, what you achieved here is amazing, a big thank you.

I'm mostly working with webcams (dshow/avfoundation) and there are certain things that need to be considered:

InputOptions.frameRate should be typed as Number. there are webcam modes with fps like 29.97, 30.00003 etc. and the capture fails if these numbers are rounded to int (29 or 30).

**Comment by tuarua** [comment]
I will fix this shortly

**Comment by tuarua** [comment]
This should now be fixed in 0.0.6 OSX / WIN version
