### ISSUE TITLE
InputOptions.vcodec

### ISSUE THREAD

**Issue by Igazine** [tuarua/AVANE#6]
still webcams related issue :)

many webcams provide their streams in different video codecs, so it would be nice to have the possibility to select them. for certain modes only one can be selected, and must be selected

ffmpeg command like looks like this:
ffmpeg -f dshow -vcodec mjpeg -s 1280x720 -i video=My Webcam Device 

Possible vcodec values for webcams (that i know of): mjpeg, rawvideo, h264

**Comment by tuarua** [comment]
If I understand correctly I am missing the ability to specify codec on input ?

**Comment by Igazine** [comment]
yes.

sometimes if you don't specify the input video codec the capture fails. also some cameras have the same resolution with different codecs ( mjpeg and rawvideo both for 1280x720 for example )

**Comment by tuarua** [comment]
This should now be fixed in 0.0.6 OSX / WIN version
