### ISSUE TITLE
AVANE.swc bytecode error

### ISSUE THREAD

**Issue by Igazine** [tuarua/AVANE#7]
At compiling my AS project I receive the following errors

`AVANE.swc(com.tuarua.ffmpeg:InputOptions): Error: abc bytecode decoding failed.`

`AVANE.swc(com.tuarua.ffmpeg:OutputOptions): Error: abc bytecode decoding failed.`

After these errors, there's hundreds more, but it's unrelated, since the problem is with the swc, therefore the entire compile process fails.

Something's not right with the latest swc, the previous one is working fine.

**Comment by tuarua** [comment]
Ok will check it out this evening.
Is this on mac or Windows? What IDE are you using ?

**Comment by tuarua** [comment]
I think I may have been using AIR SDK 24 Beta in my Flash Builder when making my last set of changes.
It could be that. Will build again this evening with 23

**Comment by Igazine** [comment]
It's on Windows (will test it on Mac later, but I assume it'll be the same)

I'm using FlashDevelop on Win, text editor and command line compile on Mac

**Comment by Igazine** [comment]
Yeah, that's possibly the reason

**Comment by tuarua** [comment]
I think I've solved the issue.
Turns out declaring something as Vector.<*> is a problem
Changed in 0.0.7 to Array
