### ISSUE TITLE
UniversalPlayer failed to seek and play

### ISSUE THREAD

**Issue by samchild** [tuarua/AVANE#8]
It seems that when you seek a few times( like 5 or 6 times), then then player will will failed to seek and play. It just showing the loading and the last picture before you seek.

It seems to  add 
`if(!streamer.connected){
				streamer.init();
				OutputOptions.uri = "tcp:127.0.0.1:1234";
				avANE.encode();
				seekAfterEncodeFinish=false;
			}`
to the onSeek function in the UniversalPlayer will fixed it.

**Comment by tuarua** [comment]
ok, will have a look

**Comment by tuarua** [comment]
This should now be fixed in latest
