### ISSUE TITLE
AVANE Global Options Error

### ISSUE THREAD

**Issue by rjx444** [tuarua/AVANE#9]
Hi there,
I'm currently facing this issue with the AVANE in android and it says:

`ReferenceError: Error #1065: Variable com.tuarua.ffmpeg::GlobalOptions is not defined.`

I'm using the AVANE-android.ane file that is included.  Hope you can help me with this since I badly needed this extension.

Best Regards,
Raymond

**Comment by tuarua** [comment]
Are you getting that error when running the example or your own written code ?
Which IDE are you using ?

**Comment by rjx444** [comment]
Yes I'm using the sample code in android. I am using flash builder 4.6..

**Comment by tuarua** [comment]
Does it say which file that error is occurring in ?
If you can give me the full console output.

Which AIR SDK are you using ?
Can you check all paths to the ANE are correct. Eg you may need to re-add the ANE if it is referencing a path as it was on my machine.
Are you debugging on a physical Android device ?

**Comment by tuarua** [comment]
Have you checked out the very latest code?

**Comment by rjx444** [comment]
This is the full error code:

```
ReferenceError: Error #1065: Variable com.tuarua.ffmpeg::GlobalOptions is not defined.
	at _AVAneTesting_FlexInit$/init()
	at mx.managers::SystemManager/http://www.adobe.com/2006/flex/mx/internal::kickOff()[/Users/justinmclean/Documents/ApacheFlex4.15/frameworks/projects/framework/src/mx/managers/SystemManager.as:2823]
	at mx.managers::SystemManager/http://www.adobe.com/2006/flex/mx/internal::preloader_completeHandler()[/Users/justinmclean/Documents/ApacheFlex4.15/frameworks/projects/framework/src/mx/managers/SystemManager.as:2731]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at mx.preloaders::Preloader/timerHandler()[/Users/justinmclean/Documents/ApacheFlex4.15/frameworks/projects/framework/src/mx/preloaders/Preloader.as:572]
	at flash.utils::Timer/_timerDispatch()
	at flash.utils::Timer/tick()
```

So far I already updated the ane file on the test project I've made to test the ANE. My current Flex SDK is Apache Flex SDK 4.15 Air23 FlashPlayer23, it is the current latest flex sdk.

**Comment by Igazine** [comment]
Make sure you update the ANE, SWC and the uncompressed ANE as well.
It's working fine for me

**Comment by rjx444** [comment]
I already updated the ANE in the test project I'm making with the latest one, the same with the swc file. But I don't have any idea about the uncompressed ane. I only added the swc and the ane file in the project. But still the error says the same.

**Comment by rjx444** [comment]
Hi sir igazine,
Can you identify whats the problem? I really need this ane. Thanks for your help

**Comment by rjx444** [comment]
Or can you give me sample flash builder project that works on your side with the ane? Just a simple project sir that is attached to the ane.. thanks

**Comment by Igazine** [comment]
I've just opened the example app and after added the newly downloaded ANE and SWC it compiles perfectly. Not sure what can be wrong on your end, maybe remove the swc and ane from the project, clean it and start over by adding them again

**Comment by tuarua** [comment]
Can you build the example Flash Builder Android app that is included in git? Looks like you are using Flex and possibly initialising the ANE in the preloader, from what the error tells me.
It's hard to know how your code is setup as when I first asked you didn't tell me you had brought it into a Flex project and hadn't first built the example provided.
Also you don't need to include the swc in Flash Builder, just the ANE as it is self contained.

**Comment by rjx444** [comment]
Hi sir tuarua,
I'm really sorry I forgot to mention before that I am using Flash builder. I tried to import the flash builder android project in the app but unfortunately the application file is missing and can't build the project.

**Comment by rjx444** [comment]
Hi sir igazine,
Are you using the Flash builder when you opened the app?

**Comment by rjx444** [comment]
Hi sir tuarua,
I'm really sorry for the confusion. I tried to import the example flash builder android app from the git but unfortunately there seems an issue and can't import it successfully. here is the error:

![scr1](https://cloud.githubusercontent.com/assets/12758745/20653644/d177d322-b54b-11e6-8e9f-ec42fd33a837.png)

As for my code setup in flash builder, I tried to add the intialization in the onComplete event and also tried on the AddedToStage event but still the error occurs. Am I doing it right sir? Or on what specific event in flex shall I initialize it?
Thanks

**Comment by Igazine** [comment]
Yes, I've opened the example app in FlashBuilder.

I also created 2 new applications for Android and desktop in FlashDevelop, and gotta say, except some minor issues I posted about in here, I have nothing but success with AVANE. It's very well programmed, easy to use, has descriptive functions and properties, it really is a great work.

Maybe the best for you if you start over, delete everything, check out AVANE again and see where it goes from there.

**Comment by rjx444** [comment]
Hi sir igazine,
Can you give me your sample test project sir? I'll try to import on my side and see how it goes. I already created a new test project to test the ANE and also re attached the ANE and make sure everything is on its proper place. I just even have this line of code in my main view file:

![scr1](https://cloud.githubusercontent.com/assets/12758745/20665687/82f79ad4-b59b-11e6-9783-52ebac34be77.png)

And as you can see still the error on my side occurs. :( hope you can help with this good sir. Thanks

**Comment by tuarua** [comment]
I will upload a basic Flex example tonight.
Haven't used Flex in a long time.
The example on github is a pure as3 project which is why you may be having trouble with it.

**Comment by rjx444** [comment]
Hi sir tuarua,
Thank you so much sir. It would really give a great help :)
Best Regards,
Raymond

**Comment by tuarua** [comment]
please see issue9.zip file. I've tested and this works on my Android phone.
[issue9.zip](https://github.com/tuarua/AVANE/files/617367/issue9.zip)

**Comment by rjx444** [comment]
Hi sir tuarua,
I already tested the sample project that you've given and it working on my side. I was just wondering why is that in my test project its not working but anyways thanks sir. Really appreciate your help :)
